name: test

on:
  push: ~
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        run: ./node_modules/.bin/alsatian ./**/**/**/*.spec.ts --tap
